1. Критерий управляемости и наблюдаемости


In [1]:
import numpy as np

print("Заполните матрицу А построчно: ")
rows = int(input("Введите количество строк: "))
cols = int(input("Введите количество столбцов: "))
A = np.array([list(map(int, input(f"Строка {i+1}: ").split()))
                  for i in range(rows)])
print("Введите вектор-столбец B:")
B = np.array([list(map(int, input(f"Строка {i+1}: ").split()))
                  for i in range(1)]).reshape(-1,1)
print("Введите строку С:")
C = np.array([list(map(int, input(f"Строка {i+1}: ").split()))
                  for i in range(1)])
B1 = B.copy()
C1 = C.copy()
Su = np.zeros((len(A[0]),len(A[0])),dtype=int) #Матрица управления
Su[:,0] = B.reshape(3)
Sn = np.zeros((len(A[0]),len(A[0])),dtype=int) #Матрица наблюдения
Sn[0,:] = C

for i in range(1,len(A[0])):
  Su[:,i] = np.dot(A,B1.reshape(3))
  B1 = np.dot(A,B1)
for i in range(1,len(A[0])):
  Sn[i,:] = np.dot(C1,A)
  C1 = np.dot(C1,A)
print(f"Матрица управления\n{Su},\nМатрица наблюдения\n{Sn}")

ru = np.linalg.matrix_rank(Su)
print(f"Ранг матрицы управления:{ru}")
if 0< np.linalg.matrix_rank(Su)< len(A[0]):
  print("Система частично управляема")
elif np.linalg.matrix_rank(Su) == len(A[0]):
  print("Система полностью управляема")
else:
  print("Система неуправялема")

rn = np.linalg.matrix_rank(Sn)
print(f"Ранг матрицы наблюдения:{rn}")
if 0< np.linalg.matrix_rank(Sn)< len(A[0]):
  print("Система частично наблюдаема")
elif np.linalg.matrix_rank(Sn) == len(A[0]):
  print("Система полностью наблюдаема")
else:
  print("Система ненаблюдаема")

Заполните матрицу А построчно: 
Введите количество строк: 3
Введите количество столбцов: 3
Строка 1: 1 2 3
Строка 2: 2 3 4
Строка 3:  4 5 6
Введите вектор-столбец B:
Строка 1: 2 2 2
Введите строку С:
Строка 1: 1  2 2
Матрица управления
[[  2  12 138]
 [  2  18 198]
 [  2  30 318]],
Матрица наблюдения
[[  1   2   2]
 [ 13  18  23]
 [141 195 249]]
Ранг матрицы управления:2
Система частично управляема
Ранг матрицы наблюдения:3
Система полностью наблюдаема


2. Приведение к диагональному виду


In [2]:

print("Заполните матрицу А построчно: ")
rows = int(input("Введите количество строк: "))
cols = int(input("Введите количество столбцов: "))
A = np.array([list(map(int, input(f"Строка {i+1}: ").split()))
                  for i in range(rows)])
print("Введите вектор-столбец B:")
B = np.array([list(map(int, input(f"Строка {i+1}: ").split()))
                  for i in range(1)]).reshape(-1,1)
print("Введите строку С:")
C = np.array([list(map(int, input(f"Строка {i+1}: ").split()))
                  for i in range(1)])
eigenvalues, eigenvectors = np.linalg.eig(A)

sorted_indices = np.argsort(eigenvalues)
L = np.diag(eigenvalues[sorted_indices]).astype(complex)
R = eigenvectors[:, sorted_indices]
print(L,'\n',R)
Bd = np.dot(np.linalg.inv(R),B) # управляемость
Cd = np.dot(C,R) # наблюдаемость
print(f"Матрица В диагональная \n{Bd} \nМатрица С диагональная \n{Cd}")

tolerance = 1e-10
for i in range(0,len(Bd)):
  if np.abs(Bd[i,0]) < tolerance:
    print(f"Система не управляема по {i+1} координате")
  else:
    print(f"Система управляема по {i+1} координате")
for i in range(0,len(Cd[0])):
  if np.abs(Cd[0,i]) < tolerance:
    print(f"Система не наблюдаема по {i+1} координате")
  else:
    print(f"Система наблюдаема по {i+1} координате")


Заполните матрицу А построчно: 
Введите количество строк: 3
Введите количество столбцов: 3
Строка 1: 1 2 3
Строка 2: 2 3 4
Строка 3: 4 5 6
Введите вектор-столбец B:
Строка 1: 2 2 2
Введите строку С:
Строка 1: 1 2 2
[[-8.30951895e-01+0.j  0.00000000e+00+0.j  0.00000000e+00+0.j]
 [ 0.00000000e+00+0.j  1.01486082e-16+0.j  0.00000000e+00+0.j]
 [ 0.00000000e+00+0.j  0.00000000e+00+0.j  1.08309519e+01+0.j]] 
 [[ 0.72770285  0.40824829  0.34416959]
 [ 0.27580256 -0.81649658  0.49532111]
 [-0.62799801  0.40824829  0.79762415]]
Матрица В диагональная 
[[ 1.13851610e+00]
 [-3.88578059e-15]
 [ 3.40384107e+00]] 
Матрица С диагональная 
[[ 0.02331195 -0.40824829  2.93006012]]
Система управляема по 1 координате
Система не управляема по 2 координате
Система управляема по 3 координате
Система наблюдаема по 1 координате
Система наблюдаема по 2 координате
Система наблюдаема по 3 координате
